var allAttributes = [	"smoker",
						"was a school bully",
						"wants to be a figher pilot",
						"loves four-wheeling in his truck",
						"wants to be the next host of the bachelor",
						"dances too close",
						"cheats on tests",
						"great listener",
						"believes the earth is flat",
						"TEST9",
						"TEST10",
						"TEST11",
						"TEST12",
						"TEST13",
						"TEST14"]