var allAttributes = [	"smoker",
						"was a school bully",
						"wants to be a figher pilot",
						"loves four-wheeling in his truck",
						"wants to be the next host of the bachelor",
						"dances too close",
						"cheats on tests",
						"great listener",
						"believes the earth is flat",
						"speaks 5 languages",
						"professional tennis player",
						"wants 10 dogs",
						"frat bro",
						"trust fund baby",
						"sings like an angel",
						"doesn't vote",
						"mansplainer",
						"lives in a pigsty",
						"gym rat",
						"gets around via hoverboard",
						"has been arrested 5 times",
						"pretend feminist",
						"bites when angry",
						"cuddly",
						"milk out of your nose funny",
						"obsessed with scary movies",
						"former fashion model",
						"parents love him",
						"amazing chef",
						"always has the hiccups",
						"talks with his mouth full always",
						"blames his farts on you",
						"knows no home appliance usages",
						"has soft hands... too soft",
						"steals your clothes",
						"goal in life is to have frosted tips",
						"refuses to take public transit",
						"can't spell but not because he is dyslexic",
						"only reads fanfiction",
						"has been on the bachelor",
						"can't ride a bike",
						"is legitimately scared of vampires",
						"thinks microwaves cause cancer",
						"volunteers with the homeless",
						"loves puppies",
						"always does the dishes",
						"has even eyebrows",
						"is deadly allergic to all your favorite foods",
						"dangerously clumsy",
						"only form or dancing is break-dancing",
						"loves coldplay",
						"only uses febreeze on his clothes",
						"always wins at videogames",
						"sore loser",
						"gives good hugs",
						"likes expensive things",
						"comes from a big family",
						"asks you for your code",
						"cuts you off in conversations",
						"sophomore with my credits",
						"always drinking protein shakes",
						"a 'did you know' guy",
						"chivalrous",
						"super artsy",
						"leaves toilet lid up",
						"pees with door open",
						"grossed out by periods",
						"brings you flowers",
						"shaves his legs",
						"incredibly smart"]