var allAttributes = [	"smoker",
						"was a school bully",
						"wants to be a figher pilot",
						"loves four-wheeling in his truck",
						"wants to be the next host of the bachelor",
						"dances too close",
						"cheats on tests",
						"great listener",
						"believes the earth is flat",
						"speaks 5 languages",
						"professional tennis player",
						"wants 10 dogs",
						"frat bro",
						"trust fund baby",
						"sings like an angel",
						"doesn't vote",
						"mansplainer",
						"lives in a pigsty",
						"gym rat",
						"gets around via hoverboard",
						"has been arrested 5 times",
						"pretend feminist",
						"bites when angry",
						"cuddly",
						"milk out of your nose funny",
						"obsessed with scary movies",
						"former fashion model",
						"parents love him",
						"amazing chef",
						"always has the hiccups"]